version: '3.8'

services:
  api:
    build: .
    ports:
      - "8004:8004"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload
